backend/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import user_views 

# imports to serve the media files
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', user_views.index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

products/urls.py
from django.urls import path
from .views import user_views, admin_views, json_views

app_name = 'products'

urlpatterns = [
    # customer
    path('', user_views.index, name='index'),
    path('products-overview/', user_views.products, name='products'),
    path('about/', user_views.about, name='about'),
    path('clothing/', user_views.clothing, name='clothing'),
    path('garniture/', user_views.garniture, name='garniture'),
    path('location/', user_views.location, name='location'),
    path('news-letter/', user_views.newsletter, name='news-letter'),
    path('search/', user_views.search, name='search'),
    path('search-results/<query>/', user_views.search_results, name='search-results'),
    path('item/<product_pk>/', user_views.item, name='item'),
    path('category/<int:mid_category_pk>/', user_views.mid_category_products, name='category-products'),
    # admin
    path('upload-content/', admin_views.admin_upload_product, name='upload-content'),
    path('confirm-sale/<int:product_pk>/', admin_views.admin_product_sold, name='confirm-sale'),
    path('create-top-category/', admin_views.admin_create_top_category, name='create-top-category'),
    path('create-category/', admin_views.admin_create_mid_category, name='create-category'),
    path('create-subcategory/', admin_views.admin_create_bottom_category, name='create-subcategory'),
    path('edit-category/<int:category_pk>/', admin_views.admin_edit_category, name='edit-category'),
    path('update-product/<int:product_pk>/', admin_views.admin_update_product, name='update-product'),
    path('dashboard/', admin_views.admin_dashboard, name='dashboard'),
    # json
    path('newsletter/', json_views.newsletter, name='newsletter'),
    path('search-autocomplete/', json_views.search_autocomplete, name='search-autocomplete'),
]
 

products/views/admin_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.db.models import Q

from ..models import Follower, Product, ProductImage, TopCategory, MidCategory, BottomCategory, Purchase

from ..forms.admin_forms import AdminProductUploadForm, AdminSaleConfirmationForm, AdminMidCategoryCreationForm, \
                                AdminBottomCategoryCreationForm, AdminEditMidCategoryForm, AdminUpdateProductForm, \
                                AdminTopCategoryCreationForm, AdminProductImageForm


def is_superuser(user):
    """
    Checking if the user is an admin for security purposes.
    """
    return user.is_superuser
    

@login_required
@user_passes_test(is_superuser)
def admin_upload_product(request):
    """
    Admin - Sending emails to the followers upon admin new content upload.
    """
    if request.method == 'POST':
        form = AdminProductUploadForm(request.POST, request.FILES)
        image_form = AdminProductUploadForm(request.POST, request.FILES)
        if form.is_valid() and image_form.is_valid():
            product = form.save()
            images = request.FILES.getlist('extra_image')
            if images:
                for image in images:
                    product_image = ProductImage.objects.create(extra_image=image)
                    product_image.product.set([product]) 
            return redirect('products:dashboard')
        else:
            print(form.errors)
    else:
        form = AdminProductUploadForm()
        image_form = AdminProductImageForm()
        print(image_form.fields['extra_image'].required)
    context = {
                'form': form, 
                'image_form': image_form
            }
    return render(request, "admin/upload_content.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_product_sold(request, product_pk):
    """
    Admin - Confirm sale and update stock.
    """
    product = Product.objects.get(pk=product_pk)
    if request.method == 'POST':
        form = AdminSaleConfirmationForm(request.POST)
        if form.is_valid():
            Purchase.objects.create(
                quantity=form.cleaned_data['quantity'],
                product_id=product_pk
            )
            return redirect('products:dashboard')
    else:
        form = AdminSaleConfirmationForm()
    context = {'form': form, 'product': product}
    return render(request, "admin/confirm_sale.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_create_top_category(request):
    """
    Admin - Create a new unique category.
    """
    if request.method == 'POST':
        form = AdminTopCategoryCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products:dashboard')
    else:
        form = AdminTopCategoryCreationForm()
    context = {'form': form}
    return render(request, "admin/create_top_category.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_create_mid_category(request):
    """
    Admin - Create a new unique category.
    """
    if request.method == 'POST':
        form = AdminMidCategoryCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products:dashboard')
    else:
        form = AdminMidCategoryCreationForm()
    context = {'form': form}
    return render(request, "admin/create_category.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_create_bottom_category(request):
    """
    Admin - Create a new unique subcategory.
    """
    if request.method == 'POST':
        form = AdminBottomCategoryCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products:dashboard')
    else:
        form = AdminBottomCategoryCreationForm()
    context = {'form': form}
    return render(request, "admin/create_subcategory.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_edit_category(request, category_pk):
    """
    Admin - Create a new unique category.
    """
    category = MidCategory.objects.get(pk=category_pk)
    if request.method == 'POST':
        form = AdminEditMidCategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            return redirect('products:dashboard')
    form = AdminEditMidCategoryForm(instance=category)
    context = {'form': form}
    return render(request, "admin/update_category.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_update_product(request, product_pk):
    """
    Admin - Create a new unique category.
    """
    product = Product.objects.get(pk=product_pk)
    if request.method == 'POST':
        form = AdminUpdateProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:dashboard')
    form = AdminUpdateProductForm(instance=product)
    context = {'form': form}
    return render(request, "admin/update_product.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_full_purchases(request):
    """
    Admin - Purchases Page.
    """
    purchases = Purchase.objects.all()
    items_per_page = 12
    paginator = Paginator(purchases, items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page}
    return render(request, "admin/full_purchases.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_full_purchase_details(request, product_pk):
    """
    Admin - Products' Full Purchase Details Page.
    """
    purchase = Purchase.objects.get(product_id=product_pk)
    context = {'purchase': purchase}
    return render(request, "admin/full_purchase_details.html", context)


@login_required
@user_passes_test(is_superuser)
def admin_dashboard(request):
    """
    Admin - Dashboard view.
    """
    # purchase = Purchase.objects.get(product_id=product_pk)
    # context = {'purchase': purchase}
    return render(request, "admin/dashboard.html", context=None)


# no money tracking

products/views/json_views.py
from django.http import JsonResponse
from django.db.models import Q

from ..models import Product, Follower
from ..utils import is_valid_email


def newsletter(request):
    """
    This endpoint receives data from the client to create a new db entry and returns 
    a Json response to reflect the success or the failure of the operation. 
    """
    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    email = request.GET.get('email')
    confirm_email = request.GET.get('confirm_email')
    choice = request.GET.get('choice')

    if not first_name.isalpha():
        return JsonResponse({'response': 'invalid-first-name'})
    if not last_name.isalpha():
        return JsonResponse({'response': 'invalid-last-name'})
    if not is_valid_email(email):
        return JsonResponse({'response': 'invalid-email'})
    if not email == confirm_email:
        return JsonResponse({'response': 'unmatching-email'})
    if Follower.objects.filter(email=email).exists():
        return JsonResponse({'response': 'existing-email'})
    
    _, new_follower = Follower.objects.get_or_create(
        first_name=first_name,
        last_name=last_name,
        email=email,
        category=choice
    )
    if new_follower:
        response = 'success'
    else:
        response = 'failure'
    return JsonResponse({'response': response})


def search_autocomplete(request):
    """
    Search Auto Complete, suggests items based on Products and Categories.
    """
    items = None
    if 'term' in request.GET:
        query = request.GET.get('term')
        search_results = Product.objects.filter(
            Q(name__icontains=query) |
            Q(mid_category__name__icontains=query)
        ).order_by('-created_at')[:5]
        if search_results.exists():
            items = [
                (
                    item.image.url, 
                    item.name, 
                    item.price, 
                    item.mid_category.name, 
                    item.pk
                ) for item in search_results
            ]
    return JsonResponse({'items': items, 'searched': query}, safe=False)

products/views/user_views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseBadRequest
from django.core.paginator import Paginator
from django.db.models import Q

from ..models import Follower, Product, TopCategory, MidCategory, BottomCategory, ProductImage

from ..forms.user_forms import NewsLetterForm 


def index(request):
    """
    Landing Page.
    """
    return render(request, "products/index.html")


def products(request):
    """
    All Products Page.
    """
    is_admin: bool = request.user.is_superuser
    items = Product.objects.all().order_by('-created_at')
    items = [item.check_availabality() for item in items]
    items_per_page = 12
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'is_admin': is_admin}
    return render(request, "products/products.html", context)

    
def about(request): 
    """
    About Page.
    """
    return render(request, "products/about.html")


def clothing(request): 
    """
    Dresses Page.
    """
    is_admin: bool = request.user.is_superuser
    items = Product.objects.filter(top_category__name='clothing').order_by('-created_at')
    items = [item.check_availabality() for item in items]

    items_per_page = 12
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'is_admin': is_admin}
    return render(request, "products/clothing.html", context)


def garniture(request): 
    """
    Blankets Page.
    """
    is_admin: bool = request.user.is_superuser
    items = Product.objects.filter(top_category__name='garniture').order_by('-created_at')
    items = [item.check_availabality() for item in items]

    items_per_page = 12
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'is_admin': is_admin}
    return render(request, "products/garniture.html", context)


def jackets(request): 
    """
    Blankets Page.
    """
    is_admin: bool = request.is_superuser
    items = Product.objects.filter(category__name='jacket').order_by('-created_at')
    items = [item.check_availabality() for item in items]
    items_per_page = 12
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'is_admin': is_admin}
    return render(request, "products/jackets.html", context)


def newsletter(request):
    """
    News Letter Page - For vistors keen to be notified about novelties.
    """
    if request.method == 'POST':
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            follower = Follower.objects.create(
                email=form.cleaned_data['email'],
                phone=form.cleaned_data['phone'],
                category=form.cleaned_data['category']
            )
            follower.save()
            return redirect('products:index')
        else:
            print("Invalid form submission. Data:", request.POST)
    else:
        form = NewsLetterForm()
    context = {'form': form}
    return render(request, "products/newsletter.html", context)
    

def search(request):
    """
    Getting the search query written in the searchbar and 
    passing it and redirecting to the search results view.
    """
    if request.method == 'GET':
        query = request.GET.get('q')
        return redirect('products:search-results', query=query)
    return HttpResponseBadRequest("Bad Request")


def search_results(request, query):
    """
    Rendering the search results queried by the user.
    """
    items = Product.objects.filter(
        Q(name__icontains=query) |
        Q(top_category__name__icontains=query) |
        Q(mid_category__name__icontains=query) |
        Q(bottom_category__name__icontains=query)
    ).order_by('-created_at')

    items_per_page = 4
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')

    items = paginator.get_page(page_number)

    context = {
        'searched': query,
        'items': items,
    }
    return render(request, 'products/search.html', context)

    

def item(request, product_pk):
    """
    Item/Product view.
    """
    item = Product.objects.get(pk=product_pk)
    images = None
    item_images = item.images
    if item_images.exists():
        images = item.images.all()
    context = {'item': item, 'images': images}
    return render(request, "products/item.html", context)


def mid_category_products(request, mid_category_pk):
    """
    Shows a specific mid category products.
    """
    # check if the category has a sub-category
    # if MidCategory.objects.filter(bottom_category__is_null=False):
    items = Product.objects.filter(mid_category_id=mid_category_pk)
    bottom_categories = BottomCategory.objects.filter(mid_category_id=mid_category_pk)
    mid_category = MidCategory.objects.get(pk=mid_category_pk)
    top_category = mid_category.top_category
    results_no = items.count()
    items_per_page = 12
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page, 
        'results_no': results_no,
        'top_category': top_category,  
        'mid_category': mid_category,
        'bottom_categories': bottom_categories
    }
    return render(request, "products/category.html", context)


def location(request):
    """
    
    """
    context = {'': ''}
    return render(request, "products/location.html", context)

frontend/templates/products/category.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    <title>Couvertures</title>
{% endblock title %}
{% block styles %}
    <link rel="stylesheet" href="{% static "css/category.css" %}">
    <link rel="stylesheet" href="{% static "css/filter_category.css" %}">
{% endblock styles %}
{% block image_url %}
    <style>
        .product-image-background {
            background-image: url('/static/css/images/dresses.jpg'); 
            /* background-image: url('{{ mid_category.image.url }}');  */
            background-color: #cccccc;
            height: 50vh;
            width: 70%;
            background-repeat: no-repeat;
            background-size: 100% 100%; 
            padding: 5px;
            margin: 20px auto;
        }

    </style>
{% endblock image_url %}
{% block app_links %}
    <a href="{% url 'products:index' %}">Home</a>
    <div class="dropdown">
        <a class="hovered" id="dropdown-button" href="#">Products <span id="dropdown-symbol">&#9660;</span></a>
    </div>
    <a href="" id="subscribe-link">Subscribe</a>
    <a href="{% url 'products:location' %}">Location</a>
    <a href="{% url 'products:about' %}">About</a>
{% endblock app_links %}
{% block content %}
    <!-- {% for item in page %}
        <img src="{{item.image.url}}" alt="Not Found" style="height: 100px; width: 100px;">
        <br>
        name: {{item.name}}
        <br>
        price: {{item.price}} DA
        <br>
        stock: {{item.stock}} 
        <br>
        {% if is_admin %}
            <a href="{% url 'products:confirm-sale' item.pk %}">Sell</a>
        {% endif %}
        <hr>
    {% endfor %} -->
    <!-- <div style="background-color: #f0efef; margin: 0; padding: 1px;"> -->
    <div class="page-path">
        <h4>{{top_category}} > {{mid_category}}</h4>
    </div>    
    <div class="product-image-background"></div>
    <div class="category-grid">
        <div class="category-name">
            <h1>{{mid_category}}</h1>
        </div>
        <div class="category-description">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti atque quidem enim laudantium, quibusdam obcaecati dicta nobis eius fugit necessitatibus praesentium. Dolor natus vel, eius vitae minus voluptates iure sed?</p>
        </div>
    </div>
    <div id="filterbar" class="bar">
        <div class="left-section">
            <h3>{{results_no}} {{mid_category}}</h3>
        </div>
        <div class="middle-section">
            {% if bottom_categories %}
                {% for category in bottom_categories %}
                    <a class="sub-category" href="#">{{category}}</a>
                {% endfor %}
            {% endif %}
        </div>
        <div class="right-section">
            <img src="/static/icons/filter.svg" alt="Filter Icon" width="20" height="20">
            <a class="filter-link" style="display: block;">Sort & Filter</a>
        </div>
    </div>
    <div id="sidebar" class="sidebar">
        <div class="sidebar-content">
            <div class="close">&times;</div>
            <h3>Color</h3>
        </div>
    </div>                                                                       
    <div class="products-grid">
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>        
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true" alt="Photo 1">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
        <div class="product">
            <img src="https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww" alt="Photo 2">
            <div class="product-details">
                <p>Name 1</p>
                <p>some other details</p>    
            </div>
        </div>
    </div>
    <button class="infinite-scroll centered-element" type="submit">View More</button>
        
{% endblock content %}

frontend/templates/products/clothing.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    <title>Clothing</title>
{% endblock title %}
{% block styles %}
    <link rel="stylesheet" href="{% static "css/top-category.css" %}">
    <link rel="stylesheet" href="{% static "css/filter_category.css" %}">
{% endblock styles %}
{% block app_links %}
    <a href="{% url 'products:index' %}">Home</a>
    <div class="dropdown">
        <a class="hovered" id="dropdown-button" href="#">Products <span id="dropdown-symbol">&#9660;</span></a>
    </div>
    <a href="" id="subscribe-link">Subscribe</a>
    <a href="{% url 'products:location' %}">Location</a>
    <a href="{% url 'products:about' %}">About</a>
{% endblock app_links %}
{% block content %}
<div class="page-path">
    <h4>Clothing</h4> 
</div>
<div class="clothing-background"></div>
<div class="clothing-jumbotron">
    <h1>Clothing</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aspernatur error reiciendis delectus aliquid, quas, amet aut perferendis sit commodi non odio architecto eligendi temporibus, accusamus beatae illo totam ratione neque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur eum voluptatem voluptatibus vel? Aut saepe, assumenda accusamus ea dolor mollitia et, asperiores quibusdam magnam eaque eligendi quisquam debitis officiis sunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div id="filterbar" class="bar">
    <div class="left-section">
        <h3>111 results</h3>
    </div>
    <div class="middle-section">
        {% for category in clothing %}
            <a class="sub-category" href="{% url 'products:category-products' category.pk  %}">{{category}}</a>
        {% endfor %}
    </div>
    <div class="right-section">
        <img src="/static/icons/filter.svg" alt="Filter Icon" width="20" height="20">
        <a class="filter-link" style="display: block;">Sort & Filter</a>
    </div>
</div>
<div id="sidebar" class="sidebar">
    <div class="sidebar-content">
        <div class="close">&times;</div>
        <h3>Color</h3>
    </div>
</div>                                                                       
<div class="image-grid">
    <div class="grid-item">
        <img src="https://media.4rgos.it/s/Argos/tuc140150182_R_SET?$Main768$&w=620&h=620" alt="Image 1">
        <h3>Dresses</h3>
    </div>
    <div class="grid-item">
        <img src="https://www.pjpan.co.uk/media/catalog/product/cache/ddc9bd1b85fcfa71e5e91929f8504b46/m/e/mens-blue-organic-tshirt_1.jpg" alt="Image 2">
        <h3>Tops</h3>
    </div>
    <div class="grid-item">
        <img src="https://images.asos-media.com/products/asos-design-oversized-t-shirt-with-racing-car-graphic-in-washed-cream/205436418-1-cream/?$n_480w$&wid=476&fit=constrain" alt="Image 3">
        <h3>Trousers</h3>
    </div>
    
    <div class="grid-item">
        <img src="https://images.asos-media.com/products/asos-design-oversized-t-shirt-with-racing-car-graphic-in-washed-cream/205436418-1-cream/?$n_480w$&wid=476&fit=constrain" alt="Image 3">
        <h3>Hats</h3>
    </div>
    <div class="grid-item"><img src="https://media.4rgos.it/s/Argos/tuc140150182_R_SET?$Main768$&w=620&h=620" alt="Image 1"></div>
    <div class="grid-item"><img src="https://www.pjpan.co.uk/media/catalog/product/cache/ddc9bd1b85fcfa71e5e91929f8504b46/m/e/mens-blue-organic-tshirt_1.jpg" alt="Image 2"></div>

    <div class="grid-item"><img src="https://www.pjpan.co.uk/media/catalog/product/cache/ddc9bd1b85fcfa71e5e91929f8504b46/m/e/mens-blue-organic-tshirt_1.jpg" alt="Image 2"></div>
    <div class="grid-item"><img src="https://images.asos-media.com/products/asos-design-oversized-t-shirt-with-racing-car-graphic-in-washed-cream/205436418-1-cream/?$n_480w$&wid=476&fit=constrain" alt="Image 3"></div>
    <div class="grid-item"><img src="https://media.4rgos.it/s/Argos/tuc140150182_R_SET?$Main768$&w=620&h=620" alt="Image 1"></div>

</div>
<button class="infinite-scroll centered-element">View More</button>


{% endblock content %}